<!doctype html>

<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>Assignment 04 - Contrasting Team Member</title>

	<!-- Custom Style Sheets -->
	<link rel="stylesheet" href="css/styles.css">
	<link rel="stylesheet" href="css/navigation.css">
	<link rel="stylesheet" href="css/banner.css">
	<link rel="stylesheet" href="css/contrast.css">

	<!-- Custom Fonts -->
	<link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Ubuntu">
	<link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto">

</head>
